### ISSUE TITLE
Patch #4 for circular references breaks etherpad

### ISSUE THREAD

**Issue by alangecker** [mconf/ep_redis_publisher#5]
due to #3 there was the patch #4 introduced which removes `_db` from the pad object to remove the unnecessary data from the message body.

obvious now in retrospect, but unfortunately not clear beforehand, it is just a reference to a pad object which might be used in different places as well. So removing `_db` from this object, means removing it globally from the pad object.

...and, yeah, it does lead to issues:

(I'm sorry for the thoughtlessly proposal in [#4 ](https://github.com/mconf/ep_redis_publisher/pull/4#issuecomment-991900674) ^^)

## Error

```
[2021-12-13 16:03:37.172] [ERROR] socket.io - Error while handling message from ea6RjjHuBf-a6nsHAAAB: TypeError: Cannot read property 'getSub' of undefined
bbb     at Pad.getRevisionDate (/opt/etherpad-lite/src/node/db/Pad.js:157:25)
bbb     at handleClientReady (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:835:33)
bbb     at processTicksAndRejections (internal/process/task_queues.js:95:5)
bbb     at async Object.exports.handleMessage (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:291:5)
bbb     at async /opt/etherpad-lite/src/node/handler/SocketIORouter.js:77:20
```

within
```js
Pad.prototype.getRevisionDate = async function (revNum) {
  return await this._db.getSub(`pad:${this.id}:revs:${revNum}`, ['meta', 'timestamp']);
};
```

## possible solutions
- deep clone objects before modifications. etherpad comes with `lodash.clonedeep` anyway, so we might us it?
  ```js
  const cloneDeep = require('lodash.clonedeep');
  [...]
  body = cloneDeep(body)
  ```
- only clone pad object with something like
  ```js
  if (body.pad && body.pad._db) {
      body = Object.assign({}, body, {
          pad: Object.assign({}, body.pad, { _db: undefined })
      })
  }
  ```

**Comment by pedrobmarin** [comment]
I think we can use [JavaScript's destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

**Comment by alangecker** [comment]
@pedrobmarin 
jeps! Without checking I simply assumed, that the destructuring assignment is only working by most recent browsers, but seems like it is supported well enough :)

```js
if (body.pad && body.pad._db) {
    body = {
       ...body,
        pad: {
            ...body.pad,
            _db: undefined
        }
    })
}
```
